# Generated by Django 4.2.7 on 2023-11-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurantId', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.TextField(max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=6)),
                ('rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('itemId', models.BigAutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=50)),
                ('category', models.CharField(choices=[('br', 'BreakFast'), ('ap', 'Appetizers'), ('sa', 'Salad'), ('bu', 'Burger'), ('pi', 'Pizza'), ('ch', 'Chicken'), ('pa', 'Pasta'), ('de', 'Dessert')], default='pi', max_length=2)),
                ('restaurantID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='rating.restaurant')),
            ],
        ),
    ]
