# Generated by Django 4.2.7 on 2023-11-10 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurantID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='rating.restaurant'),
        ),
    ]
